/**
 * This class is generated by jOOQ
 */
package biz.neustar.example.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Equipos implements Serializable {

	private static final long serialVersionUID = -760072387;

	private Integer id;
	private String  equipo;

	public Equipos() {}

	public Equipos(Equipos value) {
		this.id = value.id;
		this.equipo = value.equipo;
	}

	public Equipos(
		Integer id,
		String  equipo
	) {
		this.id = id;
		this.equipo = equipo;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getEquipo() {
		return this.equipo;
	}

	public void setEquipo(String equipo) {
		this.equipo = equipo;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Equipos (");

		sb.append(id);
		sb.append(", ").append(equipo);

		sb.append(")");
		return sb.toString();
	}
}
