/**
 * This class is generated by jOOQ
 */
package biz.neustar.example.jooq.tables.records;


import biz.neustar.example.jooq.tables.Campeones;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CampeonesRecord extends UpdatableRecordImpl<CampeonesRecord> implements Record3<Integer, String, Integer> {

	private static final long serialVersionUID = 950858226;

	/**
	 * Setter for <code>unafut.campeones.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>unafut.campeones.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>unafut.campeones.temporada</code>.
	 */
	public void setTemporada(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>unafut.campeones.temporada</code>.
	 */
	public String getTemporada() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>unafut.campeones.campeon_id</code>.
	 */
	public void setCampeonId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>unafut.campeones.campeon_id</code>.
	 */
	public Integer getCampeonId() {
		return (Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, Integer> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, Integer> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Campeones.CAMPEONES.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Campeones.CAMPEONES.TEMPORADA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Campeones.CAMPEONES.CAMPEON_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getTemporada();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getCampeonId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CampeonesRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CampeonesRecord value2(String value) {
		setTemporada(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CampeonesRecord value3(Integer value) {
		setCampeonId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CampeonesRecord values(Integer value1, String value2, Integer value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CampeonesRecord
	 */
	public CampeonesRecord() {
		super(Campeones.CAMPEONES);
	}

	/**
	 * Create a detached, initialised CampeonesRecord
	 */
	public CampeonesRecord(Integer id, String temporada, Integer campeonId) {
		super(Campeones.CAMPEONES);

		setValue(0, id);
		setValue(1, temporada);
		setValue(2, campeonId);
	}
}
