/**
 * This class is generated by jOOQ
 */
package biz.neustar.example.jooq.tables.records;


import biz.neustar.example.jooq.tables.Equipos;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EquiposRecord extends UpdatableRecordImpl<EquiposRecord> implements Record2<Integer, String> {

	private static final long serialVersionUID = 1192738801;

	/**
	 * Setter for <code>unafut.equipos.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>unafut.equipos.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>unafut.equipos.equipo</code>.
	 */
	public void setEquipo(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>unafut.equipos.equipo</code>.
	 */
	public String getEquipo() {
		return (String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, String> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, String> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Equipos.EQUIPOS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Equipos.EQUIPOS.EQUIPO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getEquipo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EquiposRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EquiposRecord value2(String value) {
		setEquipo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EquiposRecord values(Integer value1, String value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EquiposRecord
	 */
	public EquiposRecord() {
		super(Equipos.EQUIPOS);
	}

	/**
	 * Create a detached, initialised EquiposRecord
	 */
	public EquiposRecord(Integer id, String equipo) {
		super(Equipos.EQUIPOS);

		setValue(0, id);
		setValue(1, equipo);
	}
}
