/**
 * This class is generated by jOOQ
 */
package biz.neustar.example.jooq.tables;


import biz.neustar.example.jooq.Keys;
import biz.neustar.example.jooq.Unafut;
import biz.neustar.example.jooq.tables.records.EquiposRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Equipos extends TableImpl<EquiposRecord> {

	private static final long serialVersionUID = -490169364;

	/**
	 * The reference instance of <code>unafut.equipos</code>
	 */
	public static final Equipos EQUIPOS = new Equipos();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<EquiposRecord> getRecordType() {
		return EquiposRecord.class;
	}

	/**
	 * The column <code>unafut.equipos.id</code>.
	 */
	public final TableField<EquiposRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>unafut.equipos.equipo</code>.
	 */
	public final TableField<EquiposRecord, String> EQUIPO = createField("equipo", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * Create a <code>unafut.equipos</code> table reference
	 */
	public Equipos() {
		this("equipos", null);
	}

	/**
	 * Create an aliased <code>unafut.equipos</code> table reference
	 */
	public Equipos(String alias) {
		this(alias, EQUIPOS);
	}

	private Equipos(String alias, Table<EquiposRecord> aliased) {
		this(alias, aliased, null);
	}

	private Equipos(String alias, Table<EquiposRecord> aliased, Field<?>[] parameters) {
		super(alias, Unafut.UNAFUT, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<EquiposRecord, Integer> getIdentity() {
		return Keys.IDENTITY_EQUIPOS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<EquiposRecord> getPrimaryKey() {
		return Keys.KEY_EQUIPOS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<EquiposRecord>> getKeys() {
		return Arrays.<UniqueKey<EquiposRecord>>asList(Keys.KEY_EQUIPOS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Equipos as(String alias) {
		return new Equipos(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Equipos rename(String name) {
		return new Equipos(name, null);
	}
}
