/**
 * This class is generated by jOOQ
 */
package biz.neustar.example.jooq;


import biz.neustar.example.jooq.tables.Campeones;
import biz.neustar.example.jooq.tables.Equipos;
import biz.neustar.example.jooq.tables.records.CampeonesRecord;
import biz.neustar.example.jooq.tables.records.EquiposRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>unafut</code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final Identity<EquiposRecord, Integer> IDENTITY_EQUIPOS = Identities0.IDENTITY_EQUIPOS;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<CampeonesRecord> KEY_CAMPEONES_PRIMARY = UniqueKeys0.KEY_CAMPEONES_PRIMARY;
	public static final UniqueKey<EquiposRecord> KEY_EQUIPOS_PRIMARY = UniqueKeys0.KEY_EQUIPOS_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends AbstractKeys {
		public static Identity<EquiposRecord, Integer> IDENTITY_EQUIPOS = createIdentity(Equipos.EQUIPOS, Equipos.EQUIPOS.ID);
	}

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<CampeonesRecord> KEY_CAMPEONES_PRIMARY = createUniqueKey(Campeones.CAMPEONES, Campeones.CAMPEONES.ID);
		public static final UniqueKey<EquiposRecord> KEY_EQUIPOS_PRIMARY = createUniqueKey(Equipos.EQUIPOS, Equipos.EQUIPOS.ID);
	}
}
