/**
 * This class is generated by jOOQ
 */
package biz.neustar.example.jooq;


import biz.neustar.example.jooq.tables.Campeones;
import biz.neustar.example.jooq.tables.Equipos;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in unafut
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table unafut.campeones
	 */
	public static final Campeones CAMPEONES = biz.neustar.example.jooq.tables.Campeones.CAMPEONES;

	/**
	 * The table unafut.equipos
	 */
	public static final Equipos EQUIPOS = biz.neustar.example.jooq.tables.Equipos.EQUIPOS;
}
