/**
 * This class is generated by jOOQ
 */
package biz.neustar.example.jooq;


import biz.neustar.example.jooq.tables.Campeones;
import biz.neustar.example.jooq.tables.Equipos;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Unafut extends SchemaImpl {

	private static final long serialVersionUID = -1818899426;

	/**
	 * The reference instance of <code>unafut</code>
	 */
	public static final Unafut UNAFUT = new Unafut();

	/**
	 * No further instances allowed
	 */
	private Unafut() {
		super("unafut");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Campeones.CAMPEONES,
			Equipos.EQUIPOS);
	}
}
