/**
 * This class is generated by jOOQ
 */
package biz.neustar.example.jooq.tables.daos;


import biz.neustar.example.jooq.tables.Campeones;
import biz.neustar.example.jooq.tables.records.CampeonesRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CampeonesDao extends DAOImpl<CampeonesRecord, biz.neustar.example.jooq.tables.pojos.Campeones, Integer> {

	/**
	 * Create a new CampeonesDao without any configuration
	 */
	public CampeonesDao() {
		super(Campeones.CAMPEONES, biz.neustar.example.jooq.tables.pojos.Campeones.class);
	}

	/**
	 * Create a new CampeonesDao with an attached configuration
	 */
	public CampeonesDao(Configuration configuration) {
		super(Campeones.CAMPEONES, biz.neustar.example.jooq.tables.pojos.Campeones.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(biz.neustar.example.jooq.tables.pojos.Campeones object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<biz.neustar.example.jooq.tables.pojos.Campeones> fetchById(Integer... values) {
		return fetch(Campeones.CAMPEONES.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public biz.neustar.example.jooq.tables.pojos.Campeones fetchOneById(Integer value) {
		return fetchOne(Campeones.CAMPEONES.ID, value);
	}

	/**
	 * Fetch records that have <code>temporada IN (values)</code>
	 */
	public List<biz.neustar.example.jooq.tables.pojos.Campeones> fetchByTemporada(String... values) {
		return fetch(Campeones.CAMPEONES.TEMPORADA, values);
	}

	/**
	 * Fetch records that have <code>campeon_id IN (values)</code>
	 */
	public List<biz.neustar.example.jooq.tables.pojos.Campeones> fetchByCampeonId(Integer... values) {
		return fetch(Campeones.CAMPEONES.CAMPEON_ID, values);
	}
}
