/**
 * This class is generated by jOOQ
 */
package biz.neustar.example.jooq.tables.daos;


import biz.neustar.example.jooq.tables.Equipos;
import biz.neustar.example.jooq.tables.records.EquiposRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EquiposDao extends DAOImpl<EquiposRecord, biz.neustar.example.jooq.tables.pojos.Equipos, Integer> {

	/**
	 * Create a new EquiposDao without any configuration
	 */
	public EquiposDao() {
		super(Equipos.EQUIPOS, biz.neustar.example.jooq.tables.pojos.Equipos.class);
	}

	/**
	 * Create a new EquiposDao with an attached configuration
	 */
	public EquiposDao(Configuration configuration) {
		super(Equipos.EQUIPOS, biz.neustar.example.jooq.tables.pojos.Equipos.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(biz.neustar.example.jooq.tables.pojos.Equipos object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<biz.neustar.example.jooq.tables.pojos.Equipos> fetchById(Integer... values) {
		return fetch(Equipos.EQUIPOS.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public biz.neustar.example.jooq.tables.pojos.Equipos fetchOneById(Integer value) {
		return fetchOne(Equipos.EQUIPOS.ID, value);
	}

	/**
	 * Fetch records that have <code>equipo IN (values)</code>
	 */
	public List<biz.neustar.example.jooq.tables.pojos.Equipos> fetchByEquipo(String... values) {
		return fetch(Equipos.EQUIPOS.EQUIPO, values);
	}
}
